const TEMPLATES=[
{g:'Oil & Gas',n:'HH alarm ESD interlock',l:'qs',c:`{ Tank farm ESD: High-High level closes inlet valve }\nIF TK_101_LIT.PV >= TK_101_HH_SP THEN\n  TK_101_ESD.Cmd = 1;\n  XV_101_Close = 1;\nELSE\n  IF TK_101_LIT.PV < TK_101_HH_SP - 2 THEN\n    TK_101_ESD.Cmd = 0;\n  ENDIF;\nENDIF;\n`},
{g:'Oil & Gas',n:'Tank volume (strapping)',l:'cs',c:`// Cylindrical tank: m3 from level mm\ndouble dia = Me.Diameter_m;\ndouble lvl = Me.LIT.PV / 1000.0;\nMe.Volume_m3 = Math.PI * Math.Pow(dia / 2, 2) * lvl;\nMe.Volume_bbl = Me.Volume_m3 * 6.28981;\n`},
{g:'Oil & Gas',n:'Pipeline flow accumulator',l:'cs',c:`// Execute @ 1 s: m3/h to m3\nif (Me.FIT.PV > 0 && Me.FIT.PV.Quality == 192)\n{\n  Me.Total_m3 = Me.Total_m3 + Me.FIT.PV / 3600.0;\n}\n`},
{g:'Water',n:'Duty/standby pump rotation',l:'qs',c:`IF PUMP_01_Fault == 1 OR (Rotate_Timer.PV >= 86400) THEN\n  Duty_Pump = 3 - Duty_Pump;\n  Rotate_Timer.PV = 0;\nENDIF;\nPUMP_01.Cmd_Start = (Duty_Pump == 1) AND (WW_LIT.PV > Start_SP);\nPUMP_02.Cmd_Start = (Duty_Pump == 2) AND (WW_LIT.PV > Start_SP);\n`},
{g:'Water',n:'Chemical dosing feedback',l:'cs',c:`// Proportional trim on chlorine residual\ndouble err = Me.Cl2_SP - Me.Cl2_AIT.PV;\ndouble trim = Math.Max(-20, Math.Min(20, err * Me.Kp));\nMe.DosePump_Speed = Math.Max(0, Math.Min(100, Me.Base_Speed + trim));\n`},
{g:'Water',n:'Wet well level sequencer',l:'qs',c:`IF WW_LIT.PV >= 3.5 THEN PUMP_03.Cmd_Start = 1; ENDIF;\nIF WW_LIT.PV >= 2.8 THEN PUMP_02.Cmd_Start = 1; ENDIF;\nIF WW_LIT.PV >= 2.0 THEN PUMP_01.Cmd_Start = 1; ENDIF;\nIF WW_LIT.PV <= 0.8 THEN\n  PUMP_01.Cmd_Start = 0;\n  PUMP_02.Cmd_Start = 0;\n  PUMP_03.Cmd_Start = 0;\nENDIF;\n`},
{g:'Infrastructure',n:'Chiller sequencing',l:'qs',c:`DIM stages AS INTEGER;\nstages = DCP_Load_kW / CH_Cap_kW + 1;\nIF stages > 3 THEN stages = 3; ENDIF;\nCH_01.Cmd_Run = stages >= 1;\nCH_02.Cmd_Run = stages >= 2;\nCH_03.Cmd_Run = stages >= 3;\n`},
{g:'Infrastructure',n:'VFD speed ramp',l:'cs',c:`// Ramp 2 %/s toward setpoint (Execute @ 1 s)\ndouble step = 2.0;\ndouble d = Me.Speed_SP - Me.Speed_Cmd;\nMe.Speed_Cmd += Math.Abs(d) <= step ? d : Math.Sign(d) * step;\n`},
{g:'Data & mapping',n:'Historian: 24 h hourly avg',l:'sql',c:`SELECT DateTime, TagName, AVG(Value) AS AvgValue\nFROM History\nWHERE TagName IN ('TK_101_LIT.PV','FIT_201.PV')\n  AND DateTime >= DATEADD(hh,-24,GETDATE())\n  AND wwResolution = 3600000\nGROUP BY DateTime, TagName\nORDER BY DateTime;\n`},
{g:'Data & mapping',n:'S7-400FH / Modbus RTU map',l:'qs',c:`{ S7-400FH DB10.DBD4 (REAL) -> TK_101_LIT.PV\n  Modbus RTU 40001 -> holding reg 0, scale 0.1 }\nTK_101_LIT.PV = ModbusHR_0 / 10.0;\n`}];
